[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
maxRetries = 10

[deploy.release]
command = "php artisan migrate --force"
