# Railway Template Configuration

[build]
builder = "NIXPACKS"
buildCommand = "bash build.sh"

[deploy]
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
